name: Deploy with Cache-Control

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: '.'

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
      with:
        cache-control: |
          **/*.js:max-age=31536000
          **/*.css:max-age=31536000
          **/*.webp:max-age=31536000
          **/*.png:max-age=31536000
          **/*.jpg:max-age=31536000
          **/*.svg:max-age=31536000
